# Generated by Django 4.0.2 on 2022-03-23 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_article_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=2500, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='commentFather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.comment', verbose_name='Comentario Padre'),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='subcomment',
            field=models.CharField(max_length=300, verbose_name='Sub Comentario'),
        ),
        migrations.CreateModel(
            name='SubcommentLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subcomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.subcomment')),
            ],
        ),
        migrations.CreateModel(
            name='CommentLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.comment')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
