# Generated by Django 4.0.2 on 2022-04-15 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_articlelikes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='subcomment',
            options={'ordering': ['-date'], 'verbose_name': 'Sub Comentario', 'verbose_name_plural': 'Sub Comentarios'},
        ),
        migrations.AddField(
            model_name='article',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='Editado'),
        ),
        migrations.AddField(
            model_name='comment',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='Editado'),
        ),
        migrations.AddField(
            model_name='subcomment',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='Editado'),
        ),
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Seguidor')),
            ],
        ),
    ]
